import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import CircularProgress from '@mui/material/CircularProgress';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next AppTs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CircularProgress></CircularProgress>
      </main>

      {/* <footer className={styles.footer}>
      </footer> */}
    </div>
  )
}
